language: java

#env:
#  DOCKER_COMPOSE_VERSION: 1.8.0

sudo: required

services:
  - docker

dist: trusty

before_install:
  # Docker Compose Install
  - sudo apt-get update
  - docker-compose --version
  - sudo service mysql stop
  - sudo service postgresql stop
  - docker-compose up -d

install:
  - mvn install
  #- mvn clean install
  #- mvn package

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_script:
  - docker-compose stop


