language: java

#env:
#  DOCKER_COMPOSE_VERSION: 1.8.0

sudo: required

services:
  - docker

dist: trusty

before_install:
  # Docker Compose Install
  - sudo apt-get update
  #  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
  - docker-compose --version
#  - sudo rm /usr/local/bin/docker-compose
#  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
#  - chmod +x docker-compose
#  - sudo mv docker-compose /usr/local/bin
#  - docker-compose --version

before_script:
  # Disable services enabled by default
  - sudo service mysql stop
  - sudo service postgresql stop
  - docker-compose up -d
  - mvn install
  #- mvn clean install
  #- mvn package

#script:
#  - curl http://0.0.0.0:8080/Richkware-Manager-Server/

after_script:
  - docker-compose stop

after_success:
  - bash <(curl -s https://codecov.io/bash)
